---
name: Secret Test
run-name: ${{ github.actor }} is running smoke tests
on:
  workflow_dispatch:
    inputs:
      config:
        type: choice
        description: Select me
        options:
          - test
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Set Environment
        env:
          TESTRAIL_BASE_URL: ${{ secrets.TESTRAIL_BASE_URL }}
          TESTRAIL_API_KEY: ${{ secrets.TESTRAIL_API_KEY }}
          TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
        run: |
          $env_contents = @"
          TESTRAIL_BASE_URL="$env:TESTRAIL_BASE_URL"
          TESTRAIL_API_KEY="$env:TESTRAIL_API_KEY"
          TESTRAIL_USERNAME="$env:TESTRAIL_USERNAME"
          TESTRAIL_REPORT='true'
          "@
          New-item -Name .env -Value $env_contents -ItemType File -Force
          Get-Content .env
          Write-Host "Running report for most recent Beta on Windows"
          Write-Host "$env:TESTRAIL_USERNAME"
